/**
 * squashBotEval.ts — First-principles card evaluation and game state analysis.
 *
 * Replaces correlation-based card ratings with analytical ratings computed from
 * actual card effects and game economy, blended with mirror self-play signal.
 */

import type { Player } from "./player";
import { Action, Ally } from "./card";
import type { Game } from "./game";
import { MARKET_DECK } from "./data/marketDeck";
import { STARTER_DECKS } from "./data/starterDecks";
import { CHARACTER_DEFS } from "./data/characters";
import { CHARACTERS } from "./types";

// Squash Bot self-play weights (generated by selfplay.ts mirror matchups)
// Format per file: { cardName: [wins_delta, total, winRate] }
import Kelsier_sp from "./data/squash_weights/Kelsier.json";
import Shan_sp from "./data/squash_weights/Shan.json";
import Vin_sp from "./data/squash_weights/Vin.json";
import Marsh_sp from "./data/squash_weights/Marsh.json";
import Prodigy_sp from "./data/squash_weights/Prodigy.json";

type SelfPlayWeights = Record<string, number[]>;

const SELFPLAY_WEIGHTS: Record<string, SelfPlayWeights> = {
  Kelsier: Kelsier_sp as SelfPlayWeights,
  Shan: Shan_sp as SelfPlayWeights,
  Vin: Vin_sp as SelfPlayWeights,
  Marsh: Marsh_sp as SelfPlayWeights,
  Prodigy: Prodigy_sp as SelfPlayWeights,
};

// Minimum sample size before we trust a self-play weight
const SELFPLAY_MIN_SAMPLES = 100;
// How strongly to weight self-play vs analytical (additive blend)
const SELFPLAY_BLEND_STRENGTH = 80.0;

// ── Resource Base Values ──
// These are the "exchange rates" of the game economy.

const RV = {
  D: 1.0,   // damage
  M: 1.0,   // money
  Mi: 2.2,  // mission progress — primary win condition
  H: 0.5,   // heal
  C: 2.5,   // draw cards
  T: 3.0,   // training
  E: 2.0,   // eliminate
  A: 2.5,   // atium
  B: 3.5,   // extra burn
  K: 3.0,   // kill enemy ally
  R: 1.5,   // refresh
  Pc: 10.0, // permanent draw
  Pd: 8.0,  // permanent damage
  Pm: 7.0,  // permanent money
  pull: 1.5,
  push: 1.0,
  riot: 2.5,
} as const;

// ── Victory Path & Game Phase ──

export type VictoryPath = "mission" | "damage" | "hybrid";
export type GamePhase = "early" | "mid" | "late";

// ── Game State Snapshot ──

export interface MissionSnapshot {
  name: string;
  myRank: number;
  oppRank: number;
  nextThreshold: number;
  distanceToComplete: number;
  iAmAhead: boolean;
  iAmBehind: boolean;
  completed: boolean;
  oppCompleted: boolean;
}

export interface GameStateSnapshot {
  turnOrder: number;
  character: string;
  turnCount: number;

  myHealth: number;
  oppHealth: number;

  curDamage: number;
  curMoney: number;
  curMission: number;
  curBoxings: number;

  pDamage: number;
  pMoney: number;
  handSize: number;

  metalTokens: number[];
  metalAvailable: number[];
  metalBurned: number[];
  burns: number;
  atium: number;

  training: number;
  nextUnlockGap: number;

  missions: MissionSnapshot[];
  completedMissions: number;
  oppCompletedMissions: number;

  deckSize: number; // total cards: hand + discard + draw pile
  handActionCards: Action[];
  allies: Ally[];

  oppAllyCount: number;
  oppHasDefenders: boolean;
  oppTraining: number;

  victoryPath: VictoryPath;
  gamePhase: GamePhase;

  // Precomputed metal pair counts in hand
  metalPairCounts: number[]; // index by pairIdx (0-3), count of action cards in that pair
}

// ── Snapshot Builder ──

const TRAINING_UNLOCKS = [3, 5, 8, 9, 11, 13, 15, 16];

export function buildSnapshot(player: Player, game: Game): GameStateSnapshot {
  const opp = game.players[(player.turnOrder + 1) % 2];

  // Mission snapshots
  const missions: MissionSnapshot[] = game.missions.map((m) => {
    const myRank = m.playerRanks[player.turnOrder];
    const oppRank = m.playerRanks[opp.turnOrder];
    const nextTier = m.tiers.find((t) => myRank < t.threshold);
    return {
      name: m.name,
      myRank,
      oppRank,
      nextThreshold: nextTier ? nextTier.threshold : 12,
      distanceToComplete: Math.max(0, 12 - myRank),
      iAmAhead: myRank > oppRank && myRank > 0,
      iAmBehind: oppRank > myRank && oppRank > 0,
      completed: myRank >= 12,
      oppCompleted: oppRank >= 12,
    };
  });

  const completedMissions = missions.filter((m) => m.completed).length;
  const oppCompletedMissions = missions.filter((m) => m.oppCompleted).length;

  // Training unlock gap
  const nextUnlock = TRAINING_UNLOCKS.find((t) => t > player.training);
  const nextUnlockGap = nextUnlock ? nextUnlock - player.training : 99;

  // Deck size
  const deckSize = player.deck.hand.length + player.deck.discard.length + player.deck.cards.length;

  // Hand action cards
  const handActionCards = player.deck.hand.filter((c): c is Action => c instanceof Action);

  // Metal pair counts in hand
  const metalPairCounts = [0, 0, 0, 0]; // pewter/tin, bronze/copper, zinc/brass, iron/steel
  for (const card of handActionCards) {
    if (card.metal >= 0 && card.metal < 8) {
      metalPairCounts[Math.floor(card.metal / 2)]++;
    }
  }

  // Victory path — mission is the dominant strategy in most games.
  // Commit to damage when:
  //   (a) Kelsier (steel metal, +2 damage char ability), OR
  //   (b) we own a key damage engine card (House War, Crushing Blow, Maelstrom, Ruin)
  // Hybrid for characters without natural mission generation (Shan, Prodigy) —
  // they can go either way based on mid-game state.
  const DAMAGE_ENGINE_CARDS = new Set(["House War", "Crushing Blow", "Maelstrom", "Ruin"]);
  const ownedCards = [...player.deck.hand, ...player.deck.discard, ...player.deck.cards];
  const hasDamageEngine = ownedCards.some((c) => DAMAGE_ENGINE_CARDS.has(c.name));
  const isKelsier = player.character === "Kelsier";

  // Default: mission is dominant. Damage only with specific engines.
  let victoryPath: VictoryPath;
  if (isKelsier || hasDamageEngine) {
    victoryPath = "damage";
  } else {
    victoryPath = "mission";
  }

  // Flip based on actual progress when one path is clearly ahead
  const missionProgress = missions.reduce((sum, m) => sum + m.myRank / 12, 0) / 3;
  const damageProgress = (1 - opp.curHealth / 40) + player.pDamage * 0.1;
  if (victoryPath === "mission" && damageProgress > missionProgress + 0.3) {
    victoryPath = "damage";
  } else if (victoryPath === "damage" && missionProgress > damageProgress + 0.3) {
    victoryPath = "mission";
  }

  // Game phase
  let gamePhase: GamePhase = "mid";
  if (game.turncount <= 8 && player.training < 5) gamePhase = "early";
  else if (game.turncount > 20) gamePhase = "late";

  return {
    turnOrder: player.turnOrder,
    character: player.character,
    turnCount: game.turncount,
    myHealth: player.curHealth,
    oppHealth: opp.curHealth,
    curDamage: player.curDamage,
    curMoney: player.curMoney,
    curMission: player.curMission,
    curBoxings: player.curBoxings,
    pDamage: player.pDamage,
    pMoney: player.pMoney,
    handSize: player.handSize,
    metalTokens: player.metalTokens,
    metalAvailable: player.metalAvailable,
    metalBurned: player.metalBurned,
    burns: player.burns,
    atium: player.atium,
    training: player.training,
    nextUnlockGap,
    missions,
    completedMissions,
    oppCompletedMissions,
    deckSize,
    handActionCards,
    allies: player.allies,
    oppAllyCount: opp.allies.length,
    oppHasDefenders: opp.allies.some((a) => a.defender),
    oppTraining: opp.training,
    victoryPath,
    gamePhase,
    metalPairCounts,
  };
}

// ── Context-Sensitive Effect Weights ──

export function damageWeight(snap: GameStateSnapshot): number {
  let w = RV.D;
  if (snap.oppHealth <= 8) w += 3.0;
  else if (snap.oppHealth <= 15) w += 1.5;
  else if (snap.oppHealth <= 25) w += 0.5;
  if (snap.oppHasDefenders) w *= 0.7;
  if (snap.victoryPath === "damage") w *= 1.3;
  return w;
}

export function moneyWeight(snap: GameStateSnapshot): number {
  // Money is useful only when it converts to a card purchase.
  // Diminishing returns above thresholds (most cards cost 2-6).
  let w = RV.M;
  if (snap.curMoney >= 8) w *= 0.3;
  else if (snap.curMoney >= 6) w *= 0.5;
  else if (snap.curMoney >= 4) w *= 0.75;
  return w;
}

export function healWeight(snap: GameStateSnapshot): number {
  // Heal is preventive — worth more when opponent has damage pressure.
  // Base scales with current HP, then boosts when opponent is threatening.
  let w: number;
  if (snap.myHealth >= 38) w = 0.2;
  else if (snap.myHealth <= 12) w = 3.0;
  else if (snap.myHealth <= 20) w = 2.0;
  else if (snap.myHealth <= 28) w = 1.2;
  else w = 0.6;

  // Opponent damage threat: if they've already built damage engine or are dealing steady dmg
  const oppDmgPressure = (40 - snap.oppHealth) / 40; // 0-1, higher = opp is winning the dmg race
  const myHealthDeficit = (40 - snap.myHealth) / 40;
  if (myHealthDeficit > oppDmgPressure) {
    // They're hurting us faster than we're hurting them
    w *= 1.3;
  }
  return w;
}

export function missionWeight(snap: GameStateSnapshot): number {
  let w = RV.Mi * 1.3;
  if (snap.victoryPath === "mission") w *= 1.5;
  else if (snap.victoryPath === "damage") w *= 0.7;
  if (snap.completedMissions >= 2) w *= 1.8;
  return w;
}

export function trainingWeight(snap: GameStateSnapshot): number {
  if (snap.nextUnlockGap === 1) return 5.0;
  if (snap.nextUnlockGap === 2) return 3.5;
  return 2.0;
}

export function drawWeight(snap: GameStateSnapshot): number {
  return snap.gamePhase === "early" ? 3.0 : 2.0;
}

export function eliminateWeight(snap: GameStateSnapshot): number {
  // Elimination has compounding value: every Funding removed makes all future
  // draws better. Stays useful at mid-lean deck sizes (8-10).
  if (snap.deckSize >= 15) return 3.0;
  if (snap.deckSize >= 10) return 2.0;
  if (snap.deckSize >= 8) return 1.5;
  return 0.5;
}

export function killAllyWeight(snap: GameStateSnapshot): number {
  if (snap.oppAllyCount === 0) return 0;
  if (snap.oppHasDefenders) return 5.0;
  return 3.0;
}

// ── Effect Value Estimator ──
// Parses effect strings like "D.M.E" / "2.2.1" and computes context-aware value.

export function estimateEffectValue(
  effect: string,
  amount: string,
  snap: GameStateSnapshot,
): number {
  if (!effect) return 0;

  const effects = effect.split(".");
  const amounts = amount.split(".");
  let total = 0;

  for (let i = 0; i < effects.length; i++) {
    const e = effects[i];
    const a = parseFloat(amounts[i]) || 0;

    switch (e) {
      case "D": total += a * damageWeight(snap); break;
      case "M": total += a * moneyWeight(snap); break;
      case "H": total += a * healWeight(snap); break;
      case "Mi": total += a * missionWeight(snap); break;
      case "T": total += a * trainingWeight(snap); break;
      case "C": total += a * drawWeight(snap); break;
      case "E": total += a * eliminateWeight(snap); break;
      case "K": total += a * killAllyWeight(snap); break;
      case "A": total += a * RV.A; break;
      case "B": total += a * RV.B; break;
      case "R": total += a * RV.R; break;
      case "Pc": total += a * RV.Pc; break;
      case "Pd": total += a * RV.Pd; break;
      case "Pm": total += a * RV.Pm; break;
      case "pull": total += a * RV.pull; break;
      case "push": total += a * RV.push; break;
      case "riot": total += RV.riot; break;
      case "seek": total += Math.abs(a) * 0.8; break;
      case "choose": total += estimateChooseValue(amounts[i], snap); break;
      default:
        if (e.startsWith("special")) {
          total += estimateSpecialValue(e, snap);
        }
        break;
    }
  }

  return total;
}

function estimateChooseValue(optionStr: string, snap: GameStateSnapshot): number {
  // Format: "(T/1/D/2/Mi/2/H/3)" — strip parens, split, evaluate each pair
  const inner = optionStr.replace(/[()]/g, "");
  const parts = inner.split("/");
  let bestValue = 0;
  for (let i = 0; i < parts.length - 1; i += 2) {
    const effect = parts[i];
    const amount = parts[i + 1];
    const val = estimateEffectValue(effect, amount, snap);
    if (val > bestValue) bestValue = val;
  }
  return bestValue;
}

function estimateSpecialValue(special: string, snap: GameStateSnapshot): number {
  switch (special) {
    case "special1": // Investigate: +1 money per mission lowest on
      return snap.missions.filter((m) => m.iAmBehind).length * moneyWeight(snap);
    case "special2": // Eavesdrop: advance 1 on every mission lowest on
      return snap.missions.filter((m) => m.iAmBehind).length * missionWeight(snap);
    case "special3": // Lookout: draw per mission highest on
      return snap.missions.filter((m) => m.iAmAhead).length * drawWeight(snap);
    case "special4": // Hyperaware: +3 damage per mission highest on
      return snap.missions.filter((m) => m.iAmAhead).length * 3 * damageWeight(snap);
    case "special5": // Coppercloud: draw 1 if lowest on any
      return snap.missions.some((m) => m.iAmBehind) ? drawWeight(snap) : 0;
    case "special6": // House War tier 2: mission += damage, damage = 0
      return snap.curDamage * missionWeight(snap);
    case "special7": // Dominate tier 2: damage += mission, mission = 0
      return snap.curMission * damageWeight(snap);
    case "special8": // Subdue: gain market card <= 5
      return 3.0; // roughly the value of a free card
    case "special9": // Soar: buy eliminated card at cost
      return 2.0;
    case "special10": // Precise Shot: gain any eliminated card
      return 3.0;
    case "special11": // Maelstrom: kill all opp allies + clear market
      return snap.oppAllyCount * 3.0 + 2.0;
    case "special12": // Confrontation: copy eliminated action ability
      return 4.0;
    case "special13": // Confrontation tier 2: instant victory
      return 200.0;
    case "special14": // Informant: look at top, optionally eliminate
      return eliminateWeight(snap) * 0.5; // conditional eliminate
    case "special15": // Keeper: set aside a card
      return 2.0;
    case "special16": // Seeker 2: play sought card's ability
      return 3.0;
    default:
      return 2.0;
  }
}

// ── Static Analytical Card Ratings ──
// Computed once at module load from card definitions.

function computeStaticEffectValue(effect: string, amount: string): number {
  if (!effect) return 0;
  const effects = effect.split(".");
  const amounts = amount.split(".");
  let total = 0;
  for (let i = 0; i < effects.length; i++) {
    const e = effects[i];
    const a = parseFloat(amounts[i]) || 0;
    switch (e) {
      case "D": total += a * RV.D; break;
      case "M": total += a * RV.M; break;
      case "H": total += a * RV.H; break;
      case "Mi": total += a * RV.Mi; break;
      case "T": total += a * RV.T; break;
      case "C": total += a * RV.C; break;
      case "E": total += a * RV.E; break;
      case "K": total += a * RV.K; break;
      case "A": total += a * RV.A; break;
      case "B": total += a * RV.B; break;
      case "R": total += a * RV.R; break;
      case "Pc": total += a * RV.Pc; break;
      case "Pd": total += a * RV.Pd; break;
      case "Pm": total += a * RV.Pm; break;
      case "pull": total += a * RV.pull; break;
      case "push": total += a * RV.push; break;
      case "riot": total += RV.riot; break;
      case "seek": total += Math.abs(a) * 0.8; break;
      case "choose": {
        // Estimate as the average of options (bot will pick best at runtime)
        const inner = (amounts[i] || "").replace(/[()]/g, "");
        const parts = inner.split("/");
        let best = 0;
        for (let j = 0; j < parts.length - 1; j += 2) {
          const val = computeStaticEffectValue(parts[j], parts[j + 1]);
          if (val > best) best = val;
        }
        total += best;
        break;
      }
      default:
        if (e.startsWith("special")) total += 3.0; // default special value
        break;
    }
  }
  return total;
}

export interface CardEffectProfile {
  producesDamage: boolean;
  producesMission: boolean;
  producesHealing: boolean;
  producesEliminate: boolean;
  producesMoney: boolean;
  producesTraining: boolean;
}

function profileEffects(effects: string[]): CardEffectProfile {
  const all = effects.join(".");
  return {
    producesDamage: all.includes("D"),
    producesMission: all.includes("Mi"),
    producesHealing: all.includes("H"),
    producesEliminate: all.includes("E"),
    producesMoney: all.includes("M"),
    producesTraining: all.includes("T"),
  };
}

// Build static ratings for all cards, keyed by character
interface AnalyticalCardData {
  rating: number;
  profile: CardEffectProfile;
  metal: number;
  cost: number;
  isAlly: boolean;
}

const ALL_CARD_DEFS = [...MARKET_DECK, ...STARTER_DECKS];

function computeAllRatings(): {
  ratings: Record<string, Record<string, number>>;
  cardData: Record<string, AnalyticalCardData>;
} {
  // First compute base ratings (character-independent)
  const baseRatings: Record<string, number> = {};
  const cardDataMap: Record<string, AnalyticalCardData> = {};

  for (const def of ALL_CARD_DEFS) {
    if (baseRatings[def.name] !== undefined) continue; // skip duplicates

    if (def.cardType === 1) {
      // Funding
      baseRatings[def.name] = -0.3;
      cardDataMap[def.name] = {
        rating: -0.3,
        profile: { producesDamage: false, producesMission: false, producesHealing: false, producesEliminate: false, producesMoney: true, producesTraining: false },
        metal: def.metal,
        cost: def.cost,
        isAlly: false,
      };
    } else if (def.cardType === 2) {
      // Action card
      const ab1Val = computeStaticEffectValue(def.ability1Effect ?? "", def.ability1Amount ?? "");
      const ab2Val = computeStaticEffectValue(def.ability2Effect ?? "", def.ability2Amount ?? "");
      const ab3Val = computeStaticEffectValue(def.ability3Effect ?? "", def.ability3Amount ?? "");
      const burnVal = computeStaticEffectValue(def.burnEffect ?? "", def.burnAmount ?? "");
      const activeVal = computeStaticEffectValue(def.activeEffect ?? "", def.activeAmount ?? "");

      const totalEffectValue = ab1Val + ab2Val + ab3Val + burnVal + activeVal * 0.3;
      const cost = Math.max(def.cost, 1);
      const costEfficiency = totalEffectValue / cost;

      const capacity = def.ability3Effect ? 3 : def.ability2Effect ? 2 : 1;
      const capacityBonus = (capacity - 1) * 0.15;
      const flexBonus = def.metal === 8 ? 0.2 : 0;

      const rating = costEfficiency + capacityBonus + flexBonus;

      const effectStrings = [
        def.ability1Effect ?? "", def.ability2Effect ?? "", def.ability3Effect ?? "",
        def.burnEffect ?? "", def.activeEffect ?? "",
      ];

      baseRatings[def.name] = rating;
      cardDataMap[def.name] = {
        rating,
        profile: profileEffects(effectStrings),
        metal: def.metal,
        cost: def.cost,
        isAlly: false,
      };
    } else if (def.cardType === 3) {
      // Ally card
      const ab1Val = computeStaticEffectValue(def.ability1Effect ?? "", def.ability1Amount ?? "");
      const ab2Val = computeStaticEffectValue(def.ability2Effect ?? "", def.ability2Amount ?? "");
      const health = def.health ?? 0;

      const perTurnValue = ab1Val + ab2Val;
      const survivalMultiplier = health * 0.8;
      const bodyValue = health * 0.3;

      // Defenders block direct damage every turn they're alive — roughly
      // equivalent to +damage_reduction per turn. Value ~= health * turns_alive.
      const defenderBonus = def.defenseType === 'D' ? health * 4.0 : 0;

      let onPlayValue = 0;
      if (def.name === "Noble") onPlayValue = 3.5;
      if (def.name === "Crewleader") onPlayValue = 10.0;
      if (def.name === "Smoker") onPlayValue = 2.0;

      const totalAllyValue = perTurnValue * survivalMultiplier + bodyValue + defenderBonus + onPlayValue;
      const cost = Math.max(def.cost, 1);
      const rating = totalAllyValue / cost;

      const effectStrings = [def.ability1Effect ?? "", def.ability2Effect ?? ""];

      baseRatings[def.name] = rating;
      cardDataMap[def.name] = {
        rating,
        profile: profileEffects(effectStrings),
        metal: def.metal,
        cost: def.cost,
        isAlly: true,
      };
    }
  }

  // Now compute per-character ratings with synergy bonus
  const perCharRatings: Record<string, Record<string, number>> = {};

  for (const charName of CHARACTERS) {
    const charDef = CHARACTER_DEFS[charName];
    const charMetal = charDef?.ability1Metal ?? -1;
    const charRatings: Record<string, number> = {};

    const charSelfPlay = SELFPLAY_WEIGHTS[charName] ?? {};

    for (const [cardName, baseRating] of Object.entries(baseRatings)) {
      const cd = cardDataMap[cardName];
      let bonus = 0;

      if (cd && charMetal >= 0 && cd.metal >= 0) {
        if (cd.metal === charMetal) {
          bonus = 0.25; // exact metal match
        } else if (Math.floor(cd.metal / 2) === Math.floor(charMetal / 2)) {
          bonus = 0.1; // same metal pair
        }
      }

      // Blend in V2 self-play data if we have enough samples
      let selfPlayAdjust = 0;
      const spData = charSelfPlay[cardName];
      if (spData && spData[1] >= SELFPLAY_MIN_SAMPLES) {
        const winRate = spData[2];
        selfPlayAdjust = winRate * SELFPLAY_BLEND_STRENGTH;
      }

      charRatings[cardName] = baseRating + bonus + selfPlayAdjust;
    }

    perCharRatings[charName] = charRatings;
  }

  return { ratings: perCharRatings, cardData: cardDataMap };
}

const { ratings: ANALYTICAL_RATINGS, cardData: CARD_DATA } = computeAllRatings();

export { ANALYTICAL_RATINGS, CARD_DATA };
export type { AnalyticalCardData };

// ── Dynamic Card Rating ──

export function dynamicCardRating(
  cardName: string,
  character: string,
  snap: GameStateSnapshot,
): number {
  const base = ANALYTICAL_RATINGS[character]?.[cardName] ?? ANALYTICAL_RATINGS.Kelsier?.[cardName] ?? 0;
  const cd = CARD_DATA[cardName];
  if (!cd) return base;

  let adjust = 0;

  // Heal adjustment
  if (cd.profile.producesHealing) {
    const healNeed = (40 - snap.myHealth) / 40;
    adjust += (healNeed - 0.5) * 0.3;
  }

  // Damage adjustment
  if (cd.profile.producesDamage) {
    const killProximity = 1 - snap.oppHealth / 40;
    adjust += killProximity * 0.2;
    if (snap.victoryPath === "damage") adjust += 0.1;
  }

  // Eliminate adjustment
  if (cd.profile.producesEliminate) {
    const deckBloat = (snap.deckSize - 10) / 10;
    adjust += Math.max(0, deckBloat * 0.1);
  }

  // Mission adjustment
  if (cd.profile.producesMission) {
    if (snap.victoryPath === "mission") adjust += 0.15;
    if (snap.victoryPath === "damage") adjust -= 0.1;
  }

  // Metal synergy in hand
  if (cd.metal >= 0 && cd.metal < 8) {
    const pairIdx = Math.floor(cd.metal / 2);
    const pairCount = snap.metalPairCounts[pairIdx];
    adjust += Math.min(pairCount * 0.03, 0.12);
  } else if (cd.metal === 8) {
    adjust += 0.05; // atium flexibility bonus
  }

  return base + adjust;
}

// ── Metal Unlock Value ──
// What value does generating metal of this index unlock right now?
// excludeCard: when scoring a burn_card action, exclude the card being burned
// (it can't be both the fuel AND the target)

export function metalUnlockValue(
  metalIndex: number,
  player: Player,
  snap: GameStateSnapshot,
  excludeCard?: Action,
): number {
  let bestValue = 0;

  // 1. Check hand cards that could use this metal
  for (const card of snap.handActionCards) {
    if (card === excludeCard) continue;
    if (card.burned || card.metalUsed >= card.capacity) continue;
    if (card.metal !== metalIndex && !(card.metal === 8 && metalIndex === 8)) continue;

    // What tier would fire next?
    const nextTier = card.metalUsed + 1;
    const effects: [string, string][] = [
      [card.data[3], card.data[4]],
      [card.data[5], card.data[6]],
      [card.data[7], card.data[8]],
    ];
    if (nextTier >= 1 && nextTier <= 3 && effects[nextTier - 1][0]) {
      const val = estimateEffectValue(effects[nextTier - 1][0], effects[nextTier - 1][1], snap);
      if (val > bestValue) bestValue = val;
    }
  }

  // 2. Check ally abilities gated by metalBurned count
  for (const ally of snap.allies) {
    if (ally.metal !== metalIndex) continue;
    if (ally.available1 && player.metalBurned[metalIndex] === 0) {
      const val = estimateEffectValue(ally.data[3], ally.data[4], snap);
      if (val > bestValue) bestValue = val;
    }
    if (ally.available2 && player.metalBurned[metalIndex] <= 1) {
      const val = estimateEffectValue(ally.data[5], ally.data[6], snap);
      if (val > bestValue) bestValue = val;
    }
  }

  // 3. Check character ability
  const charMetal = parseInt(player.ability1metal, 10);
  if (metalIndex === charMetal && player.charAbility1 && player.training >= 5 && player.metalBurned[charMetal] === 0) {
    const val = estimateEffectValue(player.ability1effect, player.ability1amount, snap);
    if (val > bestValue) bestValue = val;
  }

  // Character ability 3 (atium-gated)
  if (metalIndex === 8 && player.charAbility3 && player.training >= 13 && player.metalBurned[8] === 0) {
    const val = estimateEffectValue("D.Mi", "3.3", snap);
    if (val > bestValue) bestValue = val;
  }

  return bestValue;
}

// ── Mission Intrinsic Scores ──

export const MISSION_INTRINSIC: Record<string, number> = {
  "Luthadel Rooftops": 0.9,
  "Kredik Shaw": 0.85,
  "Luthadel Garrison": 0.75,
  "Keep Venture": 0.7,
  "Skaa Caverns": 0.65,
  "Canton Of Orthodoxy": 0.6,
  "Pits Of Hathsin": 0.55,
  "Crew Hideout": 0.3,
};

// ── Metal Synergy: Burn Order Helper ──
// Returns the value of burning cardA to fuel cards sharing its metal pair.

export function burnSynergyValue(
  burnCard: Action,
  snap: GameStateSnapshot,
): number {
  if (burnCard.metal < 0) return 0;

  const pairIdx = burnCard.metal === 8 ? -1 : Math.floor(burnCard.metal / 2);
  let bestTargetValue = 0;

  for (const card of snap.handActionCards) {
    if (card === burnCard) continue;
    if (card.burned || card.metalUsed >= card.capacity) continue;

    // Note: previously had canFuel check here but was superseded by canFuelCorrect below.
    // See git history if needed.

    // Actually: burning a card generates metal for EITHER metal in its pair.
    // A card uses metalAvailable[card.metal]. So burning card with metal=2 generates
    // metalAvailable for bronze(2) or copper(3). Card with metal=3 would use metalAvailable[3].
    // So we need: the target card's metal to be one of the two metals in the burned card's pair.
    const canFuelCorrect =
      burnCard.metal === 8 || // atium can become any metal
      (card.metal >= 0 && card.metal < 8 && Math.floor(card.metal / 2) === pairIdx);

    if (canFuelCorrect) {
      const nextTier = card.metalUsed + 1;
      const effects: [string, string][] = [
        [card.data[3], card.data[4]],
        [card.data[5], card.data[6]],
        [card.data[7], card.data[8]],
      ];
      if (nextTier >= 1 && nextTier <= 3 && effects[nextTier - 1][0]) {
        const val = estimateEffectValue(effects[nextTier - 1][0], effects[nextTier - 1][1], snap);
        if (val > bestTargetValue) bestTargetValue = val;
      }
    }
  }

  return bestTargetValue;
}

// ── Dynamic Buffer ──

export function dynamicBuffer(character: string, snap: GameStateSnapshot): number {
  // Base buffer: how good a card must be to justify buying (and diluting the deck).
  // Higher = more selective. These are calibrated against analyticalRatings.
  const BASE_BUFFERS: Record<string, number> = {
    Kelsier: 1.5,
    Marsh: 1.8,
    Shan: 1.7,   // raised — Shan has money surplus, should be MORE selective not less
    Vin: 1.5,
    Prodigy: 1.4,
  };

  let buffer = BASE_BUFFERS[character] ?? 1.5;

  if (snap.gamePhase === "early") buffer -= 0.3;
  if (snap.curMoney >= 8) buffer -= 0.2;
  if (snap.gamePhase === "late") buffer += 0.4;
  if (snap.deckSize >= 15) buffer += 0.3;
  if (snap.deckSize >= 18) buffer += 0.5;

  return buffer;
}
